# Generated by Django 4.1.7 on 2023-02-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_comment_last_updated_alter_comment_time_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="headline",
            new_name="title",
        ),
    ]
