# Generated by Django 4.1.7 on 2023-02-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_last_updated_alter_recipe_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("Apéritif", "Apéritif"),
                            ("Plat", "Plat"),
                            ("Accompagnement", "Accompagnement"),
                            ("Accompagnement", "Accompagnement"),
                            ("Dessert", "Dessert"),
                            ("Sauce", "Sauce"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipes.recipetag",
            ),
        ),
    ]
