# Generated by Django 4.1.7 on 2023-02-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipetag_recipe_recipe_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipetag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("Apéritif", "Apéritif"),
                    ("Plat", "Plat"),
                    ("Accompagnement", "Accompagnement"),
                    ("Accompagnement", "Accompagnement"),
                    ("Dessert", "Dessert"),
                    ("Sauce", "Sauce"),
                    ("Autre", "autre"),
                ],
                default="Autre",
                max_length=20,
            ),
        ),
    ]
