# Generated by Django 4.1.7 on 2023-02-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipetag_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Apéritif", "Apéritif"),
                    ("Plat", "Plat"),
                    ("Accompagnement", "Accompagnement"),
                    ("Accompagnement", "Accompagnement"),
                    ("Dessert", "Dessert"),
                    ("Sauce", "Sauce"),
                    ("Autre", "autre"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="RecipeTag",
        ),
    ]
