# Generated by Django 4.1.7 on 2023-03-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipe_recipe_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
