# Generated by Django 4.1.7 on 2023-03-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
