# Generated by Django 4.1.7 on 2023-03-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(default="titre", max_length=128),
            preserve_default=False,
        ),
    ]
